### ISSUE TITLE
Internal Error, show index with sort conditions even if blank

### ISSUE THREAD

**Issue by ykws** [ykws/redmine_glossary#2]
![2016-11-05 7 36 10](https://cloud.githubusercontent.com/assets/5770480/20024555/ba05c0f6-a32a-11e6-8230-9de6827c9a90.png)

```ruby
2016-11-04T16:22:35.496763+00:00 app[web.1]: Completed 500 Internal Server Error in 110ms (ActiveRecord: 44.6ms)
2016-11-04T16:22:35.501576+00:00 app[web.1]: 
2016-11-04T16:22:35.501578+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::DatatypeMismatch: ERROR:  argument of WHERE must be type boolean, not type integer
2016-11-04T16:22:35.501579+00:00 app[web.1]: LINE 1: ..."glossary_styles".* FROM "glossary_styles" WHERE (1) LIMIT 1
2016-11-04T16:22:35.501580+00:00 app[web.1]:                                                              ^
2016-11-04T16:22:35.501581+00:00 app[web.1]: : SELECT  "glossary_styles".* FROM "glossary_styles" WHERE (1) LIMIT 1):
2016-11-04T16:22:35.501582+00:00 app[web.1]:   plugins/redmine_glossary/app/controllers/glossary_styles_controller.rb:35:in `edit'
2016-11-04T16:22:35.501583+00:00 app[web.1]:   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by ykws** [comment]
http://stackoverflow.com/questions/30873680/rails-testing-error-argument-of-where-must-be-type-boolean-not-type-integer

**Comment by ykws** [comment]
Only PostgreSQL.
SQLite, MySQL are no problem.
